feat: commit useEffect article
haiserve-fe/articles pull request #4
Opened 2022-08-28 15:29 UTC by LuoTuxiu

提交useEffect文章初稿

2022-08-28 16:52 UTC, CHOYSEN requested changes

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +## 为什么有 react hook
```suggestion
## 为什么有 React Hook
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +1. react class 组件书写复杂繁重，逻辑不容易复用
```suggestion
1. Class 组件书写复杂繁重，逻辑不容易复用
```
这里上下文应该都是 `react` 了

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +2. 函数组件，无法存储状态
```suggestion
2. 函数组件无法存储状态
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +effect, 翻译过来就是副作用。实际上 useEffect 就是一个函数
```suggestion
effect 翻译过来就是副作用。实际上 `useEffect` 就是一个函数。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +1. useEffect 一定要写在函数顶层吗?
```suggestion
1. `useEffect` 一定要写在函数顶层吗?
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +2. useLayoutEffect 和 useEffect 哪个先执行，destroy 呢？
```suggestion
2. `useLayoutEffect` 和 `useEffect` 哪个先执行，destroy 呢？
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +其中, fn 是副作用引发的回调函数，fn 还可以返回一个函数（会在组件卸载或者下一次更新前被调用）。deps 是依赖数组，需要开发者手动维护依赖数组。
```suggestion
其中, `fn` 是这个副作用引发的回调函数，它还可以返回一个函数（会在组件卸载或者下一次更新前被调用）。`deps` 是依赖数组，需要开发者手动维护。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +来看下 dispatcher 的结构
```suggestion
来看下 dispatcher 的结构：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +在 react 源码中，对应分了**两种 dispatcher**，比如 HooksDispatcherOnMount、比如 HooksDispatcherOnUpdate（实际还有一种专门给错误提示用的：ContextOnlyDispatcher）。
```suggestion
在 React 源码中，对应分了**两种 dispatcher**，例如 `HooksDispatcherOnMount` 和 `HooksDispatcherOnUpdate`（实际上还有一种专门给错误提示用的：`ContextOnlyDispatcher`）。
```

这里的“对应分了两种”感觉不是很通顺

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +可以看到 dispatcher 维护了 hook 的入口
```suggestion
可以看到 dispatcher 维护了 hook 的入口。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +所以，在函数组件初始化的时候，dispatcher 为 HooksDispatcherOnMount，此时会调用以下函数
```suggestion
虽然我们代码中仅仅写了 `useEffect` 一份代码，但是在源码中，实际上分了 mount 和 update 两种情形。所以在函数组件初始化的时候，dispatcher 为 `HooksDispatcherOnMount`，此时会调用以下函数：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +那么 mountEffect 又是什么函数呢
```suggestion
那么 `mountEffect` 又是什么函数呢？
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +// packages/react-reconciler/src/ReactFiberHooks.old.js
```suggestion
// https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.old.js
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +fiberEffectTag 是 fiber 定义的副作用的 tag，也就是常量，但这里很有意思的是，用的是二进制
```suggestion
`fiberEffectTag` 是 fiber 定义副作用的 tag，也就是常量，但这里很有意思的点是，它用的二进制。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +这里有几个概念，其中
这句话放在这里有点奇怪

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +比如我要表示多个副作用，比如我副作用包含 Placement 和 Update，那么 PlacementAndUpdate = Placement | Update 。按位运算还是很方便的。
```suggestion
在一次渲染任务中可能会多次使用到这里的值，那么二进制的位运算就能拉升运行时的性能。同时如果副作用包含 `Placement` 或 `Update`，我们也能很方便的从中派生出一个值进行运算：`PlacementAndUpdate = Placement | Update`。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +下面我们来看下 mountEffectImpl
```suggestion
下面我们看一下 `mountEffectImpl`：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +pushEffect 原理：
```suggestion
`pushEffect` 原理：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +pushEffect 的作用就是创建一个 Effect 对象，并把这个 Effect 对象添加到 componentUpdateQueue 中，而在初始化的时候，又把 componentUpdateQueue 添加到了 currentlyRenderingFiber 中。就是通过这样，把副作用和 fiber 产生了关联
```suggestion
`pushEffect` 的作用是创建一个 Effect 对象，并把这个对象添加到 `componentUpdateQueue` 中。在初始化的时候，我们又将 `componentUpdateQueue` 添加到 `currentlyRenderingFiber` 中，通过这样副作用就和 fiber 产生了关联。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +在函数更新的时候，会调用以下函数
```suggestion
在函数更新的时候，会调用以下函数：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +可以看到，和 mountEffectImpl 入参是一样的。
```suggestion
可以看到，这个函数和 `mountEffectImpl` 入参是一样的。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +浅比较吗？在更新时会调用到 updateEffectImpl，可以看 updateEffectImpl 的实现，其中有一段 deps 的对比，如以下：
```suggestion
浅比较吗？在更新时会调用 `updateEffectImpl`，具体可以看 `updateEffectImpl` 的实现，其中有一段 deps 的对比如下：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +可以看到，对比的逻辑是，依次取出依赖函数，并且进行 is 比较，Object.is 的实现是一个浅对比，也就是，如果你仅仅是修改了原对象的一个 key 对应的 value 值，就会导致这里并不能触发调用。解决方案是你可以使用 `{...deps}`
```suggestion
可以看到对比的逻辑是依次取出依赖函数，然后进行 is 比较，`Object.is` 的实现是一个浅对比。也就是说如果你通过可变的方式修改了对象的 value 值，那么它并不会触发副作用。取而代之的是你应该使用不可变的方式，例如对象解构： `{...deps}`。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +大家可都有个朦胧的概念是，两个副作用的回调的被调用时机是在 DOM 树被更新之后。具体执行时机还得看源码，由上一章节可以看到 useEffect/useLayoutEffect 都会在 commit 阶段被执行
```suggestion
大家都有个朦胧的概念是，两个副作用的回调的被调用时机是在 DOM 树被更新之后。具体执行时机还得看源码，由上一章节可以看到 `useEffect/useLayoutEffect` 都会在 commit 阶段被执行。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +在 commit 阶段，分为 3 大循环
```suggestion
在 commit 阶段，分为 3 大循环：
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +![react commit](./react commit.jpg)
这个图貌似没显示出来

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +是的，一定要。因为所有的 hook 都会按顺序依次维护在 hook 链表中。如果不写在顶层，比如某个 hook 加了 if 判断，此时，更新的时候，则会与上一次更新/初始化的 hook 的链表顺序不对应。
```suggestion
是的，因为所有的 hook 都会按顺序依次维护在 hook 链表中。假如你的某个 hook 不写在顶层，例如加了 `if` 判断，那么更新的时候，链表的顺序则会对不上初始化或上次更新时的顺序了。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +commitMutationEffects: 执行 DOM 操作。这里会附带一些组件的卸载，所以 useLayoutEffect 的销毁函数会在这里被调用。
```suggestion
commitMutationEffects: 执行 DOM 操作。这里会附带一些组件的卸载，所以 useLayoutEffect 的销毁函数会在这里被调用。  
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +commitLayoutEffect: DOM 树已经更新完毕了，此时会先调用 useLayoutEffect 的回调（同步），再进行 flushPassiveEffects 里面的这些 task
```suggestion
commitBeforeMutationEffects： 调度运行 flushPassiveEffects。这个调度指的是以普通优先级，被推入了 **commit 阶段后** 的 task 中，在浏览器重排/绘制后，依次调用这些回调（异步）。  
commitMutationEffects: 执行 DOM 操作。这里会附带一些组件的卸载，所以 useLayoutEffect 的销毁函数会在这里被调用。  
commitLayoutEffect: DOM 树已经更新完毕了，此时会先调用 useLayoutEffect 的回调（同步），再进行 flushPassiveEffects 里面的这些 task。
```

换行

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +useEffect 第一个参数的 function 需要返回 undefined 或者另一个 funciton
```suggestion
不能，`useEffect` 的副作用函数必须返回 `undefined` 或者 `function`。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +回答是不同逻辑，应该分开使用不同的 useEffect。componentUpdateQueue.lastEffect 也会依次存入多个副作用的回调。
```suggestion
不同逻辑应该分开使用不同的 `useEffect`，`componentUpdateQueue.lastEffect` 也会依次存入多个副作用的回调。
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +## useEffect 依赖项必填吗
```suggestion
## useEffect 依赖项是必填的吗
```

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +```
这里不是 JSX，可以贴个视频链接介绍一下 `React Forget`：https://www.youtube.com/watch?v=lGEMwh32soc&t=2s

2022-08-28 16:52 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +翻看 useEffect 的源码，会发现 Hooks 的知识，其实与 React fiber、React 渲染的流程（render/commit 阶段）息息相关，也是借助了 fiber，react 才能够在函数中实现了 Hooks 的状态的存储。所以，如果想真正了解透彻 hook 的涉及，就需要深入理解 fiber 的设计以及 react 渲染流程的原理。所以，我们接下来的源码解析将会继续学习：
```suggestion
翻看 `useEffect` 的源码，会发现 Hooks 的知识其实与 fiber 以及渲染的流程（render/commit 阶段）息息相关，也是借助了 fiber，React 才能够在函数中实现了 Hooks 的状态的存储。所以如果想真正了解透彻 hook 的涉及，就需要深入理解 fiber 的设计以及 React 渲染流程的原理。我们接下来的源码解析将会继续学习 fiber 的设计以及 React 渲染流程，敬请期待！
```

2022-08-28 16:54 UTC, CHOYSEN commented
还有一个点是有些地方是 `Hooks`，有些是 `Hook`

2022-08-28 17:00 UTC, CHOYSEN commented
写了一些小建议酌情修改哈哈，另外 `config.ts` 貌似有冲突合不了

2022-08-29 07:10 UTC, laizhenpeng commented on docs/react/useEffect/index.md
> +## useEffect 常见问题
二级标题有点多，感觉可以再划分一下，比如后面几个问答式的段落可以划分成一个模块

2022-08-29 07:12 UTC, laizhenpeng commented on docs/react/useEffect/index.md
> +先抛几个问题：
```suggestion
在使用 `useEffect` 的时候，我们可能会产生以下的疑问：
```

2022-08-29 07:14 UTC, laizhenpeng commented on docs/react/useEffect/index.md
> +相信读完本文，能够让你对这些问题有更深入的理解。
```suggestion
相信读完本文后，你能够对这些问题有更深入的理解。
```

2022-08-29 07:16 UTC, laizhenpeng commented on docs/react/useEffect/index.md
> +3. 函数无法拥有声明周期函数，因为每次都会重新调用（不像 class，是一个实例）
“不像 class，是一个实例” 这里的主语分别是谁呢

2022-08-29 07:18 UTC, laizhenpeng commented on docs/react/useEffect/index.md
> +其中, fn 是副作用引发的回调函数，fn 还可以返回一个函数（会在组件卸载或者下一次更新前被调用）。deps 是依赖数组，需要开发者手动维护依赖数组。
文章里一些句子用了英文逗号，需要改成中文逗号

2022-08-29 07:20 UTC, Lewage59 commented on docs/react/useEffect/index.md
> +为什么用二进制呢，我想原有有以下：
```suggestion
为什么用二进制呢，我想原因有以下：
```

2022-08-29 08:40 UTC, closed without merging

2022-08-29 09:22 UTC, LuoTuxiu commented on docs/react/useEffect/index.md
> +1. react class 组件书写复杂繁重，逻辑不容易复用
你说不用再提react了是吧

2022-08-29 09:47 UTC, LuoTuxiu commented on docs/react/useEffect/index.md
> +## useEffect 常见问题
好的，我分一下

2022-08-29 09:50 UTC, LuoTuxiu commented on docs/react/useEffect/index.md
> +其中, fn 是副作用引发的回调函数，fn 还可以返回一个函数（会在组件卸载或者下一次更新前被调用）。deps 是依赖数组，需要开发者手动维护依赖数组。
@laizhenpeng  这是中文逗号呢

2022-08-29 09:54 UTC, CHOYSEN commented on docs/react/useEffect/index.md
> +1. react class 组件书写复杂繁重，逻辑不容易复用
是的